import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { atomicWrite, readJson, sha256 } from "./shared.mjs";

const UPSTREAM = "https://raw.githubusercontent.com/databricks/databricks-agent-skills";
const NAMES = ["LICENSE", "NOTICE"];
const SCOPE_NAME = "THIRD_PARTY.md";
const DEFAULT_TIMEOUT_MS = 15_000;
const DEFAULT_MAX_BYTES = 256 * 1024;

export function validateSkillsVersion(value) {
  if (typeof value !== "string" || !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/.test(value)) {
    throw new Error("Legal acquisition requires the resolved exact skills semver; unknown, latest, branches and paths are forbidden.");
  }
  const prerelease = value.split("+")[0].split("-").slice(1).join("-");
  if (prerelease && prerelease.split(".").some((part) => /^\d+$/.test(part) && part.length > 1 && part.startsWith("0"))) {
    throw new Error("Skills semver prerelease numeric identifiers must not have leading zeroes.");
  }
  return value;
}

export function vendorLegalSources(version) {
  validateSkillsVersion(version);
  return Object.fromEntries(NAMES.map((name) => [name, `${UPSTREAM}/v${encodeURIComponent(version)}/${name}`]));
}

export function vendorLegalScope(version) {
  validateSkillsVersion(version);
  return `# Third-party Databricks skills\n\n` +
    `Source: https://github.com/databricks/databricks-agent-skills/tree/v${version}\n\n` +
    `Resolved upstream version: ${version}.\n\n` +
    `The adjacent LICENSE and NOTICE are exact upstream files for this version. They apply to the vendored Databricks skill files in this directory. When copied into .claude/skills/ or .github/skills/, their scope is the official databricks-* skill directories, not the separately authored harness skill directories.\n\n` +
    `This harness-generated scope document does not replace, extend, or relicense the upstream terms. Preserve LICENSE and NOTICE when redistributing the official skills. Review the license before use or distribution; its permissions and restrictions remain applicable. Any modified upstream files must retain attribution and carry the change notices required by that license.\n\n` +
    `Generated by tools/lib/vendor-legal.mjs. Upstream skill contents are not modified by this document.\n`;
}

function positiveBound(value, fallback, label, maximum) {
  const bound = value ?? fallback;
  if (!Number.isSafeInteger(bound) || bound <= 0 || bound > maximum) throw new Error(`Invalid ${label} limit.`);
  return bound;
}

async function downloadText(url, name, dependencies) {
  const timeoutMs = positiveBound(dependencies.timeoutMs, DEFAULT_TIMEOUT_MS, "download timeout", 60_000);
  const maxBytes = positiveBound(dependencies.maxBytes, DEFAULT_MAX_BYTES, "legal file size", 1024 * 1024);
  const controller = new AbortController();
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => { controller.abort(); reject(new Error(`${name} download timed out.`)); }, timeoutMs);
  });
  const read = async () => {
    const response = await (dependencies.fetch ?? globalThis.fetch)(url, { signal: controller.signal, redirect: "error" });
    if (response.status !== 200 || response.redirected) throw new Error(`${name} download returned HTTP ${response.status}; redirects are not accepted.`);
    const advertised = response.headers?.get("content-length");
    if (advertised && (!/^\d+$/.test(advertised) || Number(advertised) > maxBytes)) throw new Error(`${name} exceeds the legal file size limit.`);
    if (/text\/html/i.test(response.headers?.get("content-type") ?? "")) throw new Error(`${name} download returned HTML, not upstream legal text.`);
    if (!response.body?.getReader) throw new Error(`${name} download did not provide a readable response body.`);
    const reader = response.body.getReader();
    const chunks = [];
    let size = 0;
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        size += value.byteLength;
        if (size > maxBytes) throw new Error(`${name} exceeds the legal file size limit.`);
        chunks.push(Buffer.from(value));
      }
    } catch (error) {
      controller.abort();
      await reader.cancel().catch(() => {});
      throw error;
    } finally { reader.releaseLock(); }
    const bytes = Buffer.concat(chunks);
    let text;
    try { text = new TextDecoder("utf-8", { fatal: true }).decode(bytes); }
    catch { throw new Error(`${name} is not valid UTF-8 legal text.`); }
    if (!text.trim() || text.includes("\0") || /^\s*(?:<!doctype html|<html)/i.test(text)) throw new Error(`${name} download contained empty or invalid legal text.`);
    return bytes;
  };
  try { return await Promise.race([read(), timeout]); }
  finally { clearTimeout(timer); }
}

export async function stageVendorLegal(stagingDirectory, version, dependencies = {}) {
  const sources = vendorLegalSources(version); // Validate before filesystem or network work.
  if (!(await stat(stagingDirectory)).isDirectory()) throw new Error("Legal staging target must be an existing directory.");
  // Nothing is written unless BOTH official legal files have downloaded completely.
  const downloaded = await Promise.all(NAMES.map(async (name) => [name, await downloadText(sources[name], name, dependencies)]));
  const scope = Buffer.from(vendorLegalScope(version), "utf8");
  const files = Object.fromEntries(downloaded.map(([name, bytes]) => [name, { source: sources[name], sha256: sha256(bytes), bytes: bytes.length }]));
  files[SCOPE_NAME] = { source: "harness-generated:tools/lib/vendor-legal.mjs", sha256: sha256(scope), bytes: scope.length };
  for (const [name, bytes] of [...downloaded, [SCOPE_NAME, scope]]) await atomicWrite(join(stagingDirectory, name), bytes);
  return { schemaVersion: 1, sourceTag: `v${version}`, files };
}

export async function verifyVendorLegal(root) {
  const problems = [];
  let lock;
  let sources;
  try {
    lock = await readJson(join(root, "vendor/databricks-skills.lock.json"));
    sources = vendorLegalSources(lock.resolvedVersion);
  } catch (error) {
    return [`Invalid Databricks skills legal provenance: ${error.message}`];
  }
  const metadata = lock.legal;
  if (metadata?.schemaVersion !== 1 || metadata.sourceTag !== `v${lock.resolvedVersion}`) problems.push("Databricks skills legal metadata is missing or bound to a different version");
  for (const name of [...NAMES, SCOPE_NAME]) {
    const record = metadata?.files?.[name];
    const expectedSource = sources[name] ?? "harness-generated:tools/lib/vendor-legal.mjs";
    if (!record || record.source !== expectedSource || !/^[a-f0-9]{64}$/.test(record.sha256 ?? "") || !Number.isSafeInteger(record.bytes) || record.bytes < 1) {
      problems.push(`Invalid Databricks skills legal lock entry: ${name}`);
    }
    try {
      const path = join(root, "vendor/databricks-skills", name);
      if (!(await stat(path)).isFile()) throw new Error("not a regular file");
      const bytes = await readFile(path);
      if (!record || sha256(bytes) !== record.sha256 || bytes.length !== record.bytes) problems.push(`Databricks skills legal file missing or modified: ${name}`);
      if (name === SCOPE_NAME && sha256(bytes) !== sha256(vendorLegalScope(lock.resolvedVersion))) problems.push("Databricks skills THIRD_PARTY.md scope does not match its generator and version");
    } catch { problems.push(`Missing or unreadable Databricks skills legal file: ${name}`); }
  }
  return problems;
}
